#!/bin/sh
#
# Check for debug statements

FILES_PATTERN='\.(rb|erb|js)(\..+)?$'
FORBIDDEN='console.log\|binding.pry\|save_page'

git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN && \
    echo 'COMMIT REJECTED' && \
    exit 1

exit 0
